.github/workflows/build_patch_artifacts.yaml

- ci: add build_patch_artifacts workflow

ci: add build_patch_artifacts workflow

---

cli/src/main.rs
library/src/c_api.rs
library/src/cache.rs
library/src/config.rs
library/src/network.rs
library/src/updater.rs

- feat(updater): include version_code in release_version string

feat(updater): include `version_code` as part of `release_version`

---

.github/actions/rust_crate/action.yaml
.github/workflows/main.yaml
.gitignore

- ci: upload coverage to codecov

ci: upload coverage to codecov

---

README.md

chore: add coverage badge to README

---

COPYRIGHT
LICENSE-APACHE
LICENSE-MIT

- chore: add MIT and Apache licenses

chore: add MIT and Apache licenses

---

README.md

- chore: add licenses badges to README

chore: add licenses badges to README

---

shorebird_code_push/pubspec.yaml

Preferred for publishing to pub.dev

chore: add homepage to pubspec.yaml

---

shorebird_code_push/CHANGELOG.md
shorebird_code_push/pubspec.yaml

Adds a changelog in preparation for publishing to pub.dev

chore(shorebird_code_push): add CHANGELOG.md

---

.github/actions/flutter_package/action.yaml
shorebird_code_push/README.md

ci: exclude generated code

---

shorebird_code_push/README.md

docs: add coverage badge

---

shorebird_code_push/CHANGELOG.md
shorebird_code_push/pubspec.yaml

- chore(shorebird_code_push): v1.1.0

chore(shorebird_code_push): v1.1.0

---

library/src/android.rs
library/src/cache.rs

Refactored our android code slightly so we could test all the
branches of our "find the right split apk" function.
This may have been a waste of time.

test: improve rust coverage

---

library/Cargo.toml

chore: sort deps in Cargo.toml

---

library/include/updater.h
library/src/android.rs
library/src/c_api.rs
library/src/cache.rs
library/src/config.rs
library/src/network.rs
library/src/updater.rs

I ran `cargo clippy`.
I've not tried to configure it or make it run on PRs yet, but this
is a start.

chore: run `cargo clippy` over our rust codebase

---

shorebird_code_push/README.md

Puts the example in README.md in the context of a Flutter app.

docs(shorebird_code_push): improve example in readme

---

library/Cargo.toml
library/src/c_api.rs
library/src/config.rs
library/src/updater.rs

WIP, need to fix tests and make sure this actually works

Refactor posix file i/o to c_api

---

.github/dependabot.yml

I'm not sure if I got the syntax right for our cargo directories
or if I should just list the root directory.  But I figure
dependabot will tell me if I got it wrong.

chore: Use dependabot

---

Cargo.lock
library/Cargo.toml

Much more to remove here, but this is a start.

chore: remove unused package

---

library/README.md

Updates the README to reflect the current state of the Updater state machines.

docs: update state machine description in readme

---

updater_tools/lib/src/commands/diff_command.dart
updater_tools/lib/src/extensions/arg_results.dart
updater_tools/lib/src/packager/patch_packager.dart
updater_tools/lib/src/updater_tools_command_runner.dart
updater_tools/test/src/commands/diff_command_test.dart

Adds a diff command that is a passthrough to the `patch` executable.

feat(updater_tools): add diff command

---

.github/actions/publish_flutter_package/action.yaml
.github/workflows/publish.yaml

- chore: minor improvements to actions/workflows

chore: minor improvements to actions/workflows

---

library/src/updater.rs

With the changes to the updater to support rollback functionality, we stopped sending the current patch number, which causes the server to always send down the latest available patch, whether we already have it installed or not. This led to the `isNewPatchAvailableForDownload` method in the `shorebird_code_push_package` returning true when it shouldn't have (e.g., if the latest patch is already installed).
Part of https://github.com/shorebirdtech/shorebird/issues/2385

fix: don't return true from isNewPatchAvailableForDownload if the new patch will not be installed

---

shorebird_code_push/lib/src/shorebird_code_push_noop.dart
shorebird_code_push/test/shorebird_code_push_io_test.dart
shorebird_code_push/test/src/shorebird_code_push_noop_test.dart

This is a common source of confusion, hopefully this will help.

feat: add a longer no-op message.

---

library/src/cache/patch_manager.rs
library/src/updater.rs

Adds more/clearer logs when we decide to delete a patch.

chore: improve logging

---

shorebird_code_push/CHANGELOG.md
shorebird_code_push/pubspec.yaml

- chore(shorebird_code_push): v2.0.0-dev.2

chore(shorebird_code_push): v2.0.0-dev.2

---

shorebird_code_push/example/.metadata
shorebird_code_push/example/pubspec.yaml
shorebird_code_push/example/web/index.html

- chore(shorebird_code_push): minor improvements to example
- regenerate web
- reset pubspec version
- adjust pubspec environment constraints

chore(shorebird_code_push): minor improvements to example

---

shorebird_code_push/CHANGELOG.md
shorebird_code_push/pubspec.yaml

- chore(shorebird_code_push): v2.0.2

chore(shorebird_code_push): v2.0.2

---

library/include/updater.h
library/src/c_api/mod.rs

- fix(updater): re-export `shorebird_check_for_update` for backward compat
- closes https://github.com/shorebirdtech/shorebird/issues/2673

fix(updater): re-export `shorebird_check_for_update` for backward compat

---

library/src/updater.rs

Update `patch_base` targeting to use Windows patching method on macOS

feat: change updater to support intel macs

---

library/Cargo.toml
library/src/logging.rs

Wire up SimpleLogger on Linux to get logs in stdout

feat: configure logging on linux

---

library/src/network.rs
library/src/updater.rs

In response to customer feedback

chore: add more info-level logging around patch downloads

---

shorebird_code_push/analysis_options.yaml
shorebird_code_push/lib/shorebird_code_push.dart
shorebird_code_push/lib/src/shorebird_updater.dart
shorebird_code_push/lib/src/shorebird_updater_io.dart
shorebird_code_push/pubspec.yaml

- refactor(shorebird_code_push): upgrade analysis_options

refactor(shorebird_code_push): upgrade analysis_options

---

library/src/updater.rs
shorebird_code_push/example/pubspec.yaml
shorebird_code_push/lib/src/shorebird_updater.dart

Fixes https://github.com/shorebirdtech/shorebird/issues/2883

fix: roll back patches in check_for_downloadable_update
