cli/src/main.rs, library/include/updater.h, library/src/c_api.rs, library/src/cache.rs, library/src/config.rs, library/src/network.rs, library/src/updater.rs
The rust plumbing for adding version_code.
Renamed release_version to version_name, add version_code, removed vm_path.
Also added version_code changing as a reason to invalidate the cache dir.
=> feat: Support using Android versionCode for patch checks

.vscode/settings.json, library/src/c_api.rs, library/src/cache.rs, library/src/config.rs, library/src/updater.rs, library/tests/c_api_test.rs, library/tests/common/mod.rs, library/tests/updater_test.rs
This removes another source of possible crashes from the rust code.
I also took this opportunity to try and test the C-api. I also discovered rust "integration tests" as part of this and chose to move some of the (new) c_api tests to an integration test as well as the existing rust api (updater.rs) tests.
=> refactor: C API to avoid using unwrap.

BUILDING_ENGINE.md
Updates based on @bryanoltman's first time going through the instructions.
=> docs: update building_engine.md

library/src/c_api.rs, library/src/config.rs, library/src/lib.rs, library/src/updater.rs
Fixes https://github.com/shorebirdtech/shorebird/issues/413
Validated by:
- Creating a new Flutter project
- Running `shorebird init`
- Removing `shorebird.yaml`
- Verifying that `shorebird --local-engine-src-path=$HOME/Shorebird/engine/src --local-engine=android_release_arm64 run -- --release` doesn't panic and still launches the app.
I also tested the release-patch flow to ensure that didn't break.
- Updates `with_config` in `library/src/config.rs` to
- Return `anyhow::Result<R>` instead of `R`
- Not panic if the config object isn't initialized
- Return an error in the case where the config object isn't initialized
- Updates consumers of `with_config` to handle the possibility that `with_config` may return an error by propagating the error, usually to `log_on_error` in …
=> fix: don't panic on missing shorebird.yaml

BUILDING_ENGINE.md, library/Cargo.toml, library/src/config.rs, library/src/logging.rs
I've not actually made it fully work yet, but at least it compiles and logs work.
=> feat: Make updater build on iOS

library/src/cache.rs, library/src/config.rs, library/src/updater.rs
Each unwrap() is a potential crash.  Shorebird's updater code should never crash.
There still are a couple, but I think we should set up coverage first so we can track that we're testing all these changes.
=> fix: remove more unwrap calls.

library/include/updater.h, library/src/c_api.rs
Passes the next patch number back as a `usize` instead of a `char *`
=> chore: use a usize instead of a char* for next boot patch number

library/include/updater.h, library/src/c_api.rs, shorebird_code_push/example/lib/main.dart, shorebird_code_push/example/pubspec.yaml, shorebird_code_push/lib/src/generated/updater_bindings.g.dart, shorebird_code_push/lib/src/shorebird_code_push.dart, shorebird_code_push/lib/src/updater.dart, shorebird_code_push/test/src/shorebird_code_push_test.dart, shorebird_code_push/test/src/updater_test.dart
Adds `shorebird_current_boot_patch_number` to the Updater api, updates the example to use it.
=> feat: add shorebird_current_boot_patch_number function

.github/workflows/build_patch_artifacts.yaml
Fixes #47 
This PR downgrades the version of the GitHub Actions Ubuntu machine. The machine will use an older version of glibc to build `patch` which will fix the error users are facing.
I have tested this change on an Ubuntu 20.04 VM.
=> fix: glibc error when patching on Linux

library/src/cache.rs, library/src/updater.rs
I'm not sure if this is better or worse, but it does make testing
a bit more clear.
=> refactor: Use Result to indicate failure in mark_patch_bad

library/Cargo.toml, library/src/cache.rs
Adds a client_id field to UpdaterState, the contents of which will be a random UUID that is generated once, either on load (for existing clients) or on UpdaterState creation (for new clients).
=> feat: add client_id to UpdaterState

library/Cargo.toml, library/src/network.rs
Inspects the error message produced by our patch check request to see if it matches what we expect in cases of no internet connection. If so, log "Patch check request failed due to network error. Please check your internet connection".
Fixes https://github.com/shorebirdtech/shorebird/issues/759
=> fix: log more friendly error message in case of no internet connection

library/src/cache.rs, library/src/network.rs, library/src/updater.rs
We were previously making a blocking network request on the main thread. This moves that call to a background thread.
=> fix: put call to report launch success on bg thread.

library/src/network.rs
We directed users to look for this log, but it was no longer visible after my recent changes to reduce logging, so adding back.
https://docs.shorebird.dev/troubleshooting#how-to-fix-it-1
I don't know how to test in rust for log calls, so just leaving
a comment for now.
=> fix: show patch check info in logs

shorebird_code_push/CHANGELOG.md, shorebird_code_push/lib/shorebird_code_push.dart, shorebird_code_push/lib/src/generated/updater_bindings.g.dart, shorebird_code_push/lib/src/shorebird_code_push_io.dart, shorebird_code_push/lib/src/shorebird_code_push_web.dart, shorebird_code_push/test/shorebird_code_push_io_test.dart
Users were sometimes importing the _web version thinking it
was the "web safe" import, rather than shorebird_code_push.dart
and then being surprised when ShorebirdCodePush did nothing.
Fixes https://github.com/shorebirdtech/shorebird/issues/1209
=> refactor: move shorebird_code_push_io and _web into src/

library/src/cache.rs
Fixes issue where client_id was being regenerated when the app's release version changed or when the previous state failed to validate.
=> fix: don't regenerate client id if UpdaterState successfully loaded

library/build.rs, library/src/c_api.rs, library/src/events.rs, library/src/lib.rs, library/src/network.rs
Refactored our PatchInstallEvent to be just PatchEvent
and allow us to have more than one event type.
I moved it into its own events.rs file and added privacy
warnings to both this and the network code (eventually
we may move all this into a separate privacy.rs file).
I also fixed our build.rs file to not panic when our build
is otherwise broken. For whatever reason that seems to
cause the rust-analyzer to stop and not show any future
warnings (thus it's hard to fix things).
I moved away from having a "new" method for PatchEvent
with a series of Strings (which could be confused in order)
and instead am now using just the normal default struct
construction which effectively has named args.
Since EventType is now an enum, it's easy to use the
right enum not have to call …
=> refactor: Prepare to have more than one event type

library/src/c_api.rs, library/src/cache.rs, library/src/events.rs, library/src/network.rs, library/src/updater.rs
This doesn't tell us anything about the failure, just that it
happened.  Which at least will let us communicate that to customers.
This currently has no tests and will need some before landing.
=> feat: report patch install failure events

library/Cargo.toml, library/build.rs, library/include/updater.h, library/src/android.rs, library/src/c_api.rs, library/src/cache.rs, library/src/config.rs, library/src/events.rs, library/src/network.rs, library/src/updater.rs, library/src/updater_lock.rs, patch/src/bin/string_patch.rs
I just ran `cargo clippy -- -W clippy::pedantic` and fixed things.
These are more invasive that the default set and the remaining
warnings are mostly about our (abysmal) public docs missing
Error and Panic sections to explain errors and panicks.
=> chore: fix 30 of the 54 warnings from clippy pedantic.

library/include/updater.h, library/src/c_api.rs, library/src/cache.rs, library/src/config.rs, library/src/updater.rs
Adds a separate directory to store UpdateState (distinct from downloaded artifacts) to avoid UpdaterState getting wiped out between release versions on Android.
Part of https://github.com/shorebirdtech/shorebird/issues/1239
=> fix: add separate storage dir for state

library/src/cache.rs
Patches are sometimes failing to apply on iOS due to the reasons explained [here](https://github.com/shorebirdtech/shorebird/issues/1296#issuecomment-1728308059). In short, UpdaterState is saving its location, which is not always guaranteed to be accessible to the app, as iOS can move the app's home directory between runs.
Fixes https://github.com/shorebirdtech/shorebird/issues/1296
=> fix: don't serialize UpdaterState cache_dir as it can change between app runs

shorebird_code_push/example/lib/main.dart
With small patches, the "downloading update" banner would sometimes not be replaced with the restart banner. This change adds a delay to ensure the downloading banner has time to fully animate in before we dismiss it.
=> fix: add delay to unstick download banner

library/src/cache/patch_manager.rs
This is not an error (patches_state.json is expected to not exist on the first launch of a release) and generates a ton of log noise. Reduce the log severity to debug.
=> chore: don't error log if patches_state.json doesn't exist

shorebird_code_push/lib/src/shorebird_code_push_io.dart, shorebird_code_push/test/shorebird_code_push_io_test.dart
This log causes the following error to be printed to the console when the shorebird bindings are not available: `[ShorebirdCodePush]: Error initializing updater: Invalid argument(s): Failed to lookup symbol 'shorebird_current_boot_patch_number': undefined symbol: shorebird_current_boot_patch_number`. This error is confusing and unhelpful, especially since it is immediately followed by `[ShorebirdCodePush]: Shorebird Engine not available, using no-op implementation.`, which is clearer and more helpful.
=> chore(shorebird_code_push): remove error log when shorebird is unavailable

library/Cargo.toml, library/src/config.rs, library/src/network.rs, library/src/updater.rs
Updates the `updater.rs` tests to use stubbed network endpoints (via the [mockito](https://docs.rs/mockito/latest/mockito/) crate), which allows us to verify the number of times a given endpoint was called.
Once this lands, future PRs will update tests to use this pattern, eventually removing the `testing_set_network_hooks` functionality and potentially the `NetworkHooks` struct entirely.
=> test: use mockito crate to test network-interfacing code

library/src/cache/updater_state.rs, library/src/events.rs, library/src/network.rs, library/src/updater.rs
We added client_id back when we had a different billing model
where we would bill customers based on number of unique devices
accepting an install in a given month (similar to what expo.dev
advertised as their pricing model at the time).
We moved to a differnet pricing model and never used client_id
so removing it.
=> refactor: remove client_id

library/Cargo.toml, library/src/logging.rs
Updates logging on iOS to print rust logs to output (currently, only Flutter engine FML_LOGs are being written to the console).
Replaces the `simple_logging` crate with the `oslog` crate. I'm a bit torn on using `oslog` as it doesn't seem to be very actively contributed to or to have many stars on GitHub, but it has some pretty [high-profile users](https://crates.io/crates/oslog/reverse_dependencies), it's simple, and it seems to work, so 
Note that this exposes some error logs that we will want to clean up (probably along with https://github.com/shorebirdtech/updater/issues/119), for example: 
```
2024-02-06 15:23:23.657521-0500 Runner[674:37487] [updater::cache::updater_state] Error loading state: File /private/var/mobile/Containers/Data/Application/E15D3235-7B43-4DA8-BA71-80E83A4D448C/L …
```
=> fix: us OSLog framework for logging on iOS

patch/.cargo/config.toml
As per https://github.com/rust-lang/rust/issues/100874#issuecomment-1222405985.
The patch.exe being generated by `cargo build --release` is ~96KB larger than the artifact being downloaded by the shorebird cli, which looks to be roughly the size of some (but not all 🙃) of the VCRUNTIME140.dll files I'm finding on my system.
Fixes https://github.com/shorebirdtech/shorebird/issues/1487
=> fix(patch): update crt-static flag in build config

library/src/cache/patch_manager.rs
Removes assumption that a failed patch is `next_boot_patch` in fallback behavior.
Fixes https://github.com/shorebirdtech/updater/issues/148
=> fix: verify failed patch is next_boot_patch before clearing

Cargo.toml, library/src/cache/patch_manager.rs, library/src/cache/updater_state.rs, library/src/updater.rs
On successful boot, deletes all patch artifacts belonging to patches older than the successfully booted patch.
Also changes `record_boot_success_for_patch` to `record_boot_success`, as the patch manager now knows which patch we're recording success for.
Fixes https://github.com/shorebirdtech/updater/issues/147
=> fix: delete all old patch artifacts on successful boot

library/src/config.rs, library/src/network.rs, library/src/updater.rs, patch/src/main.rs
Update `check_for_update_internal` to no longer hold the config lock while making a patch check request.
Fixes https://github.com/shorebirdtech/shorebird/issues/1981
=> fix: Don't make network request while holding config lock

library/src/config.rs, library/src/yaml.rs
Updates Updater to read (optional) public key from release yaml.
=> feat: read public key from release yaml

library/src/cache/patch_manager.rs, library/src/cache/updater_state.rs, library/src/updater.rs
Write patch hash to disk alongside number and size.
=> feat: store patch hash on disk

Cargo.lock, library/Cargo.toml, library/src/events.rs, library/src/lib.rs, library/src/network.rs, library/src/time.rs, library/src/updater.rs
Adds `timestamp` to PatchEvent struct so we can track when events actually happened, not just when they were reproted.
Part of https://github.com/shorebirdtech/updater/issues/131
=> feat: add timestamp to patch events

library/src/network.rs, library/src/updater.rs
We had two ways of making a patch check request, but really only need one.
=> refactor: remove duplicated sent_patch_check_request code

library/src/android.rs, library/src/c_api/mod.rs, library/src/cache/patch_manager.rs, library/src/cache/updater_state.rs, library/src/config.rs, library/src/updater.rs
When validating that a patch is "good" to boot from, we compare `last_attempted_boot_patch` to `last_successfully_booted_patch`. If these are different, we assume that `last_attempted_boot_patch` failed to boot and delete it. This causes problems if we perform validation while that patch is booting (we are attempting to boot from it, but it has not yet finished booting, so we think it is bad and delete it, never giving it a chance to finish booting).
To get around this, this PR introduces `currently_booting_patch`, which causes us to skip the above step of validation and prevents us from assuming that a patch in the process of booting has previously failed to boot.
As a followup to this, we could probably delete `last_attempted_boot_patch` and use `on_init` to clean up a "failed to boot" …
=> fix: track patches while they are booting

library/src/cache/patch_manager.rs, library/src/cache/updater_state.rs, library/src/updater.rs
Removes `last_attempted_patch` from our on-disk state in favor of using `currently_booting_patch`.
`last_attempted_patch` was introduced to detect cases where a patch crashed before launch failure or success could be recorded. Due to the way we validate patches, it was possible for a patch to erroneously fail validation on its first boot if validation was performed between launch start and launch success or failure (https://github.com/shorebirdtech/updater/issues/184). https://github.com/shorebirdtech/updater/pull/185 introduced `currently_booting_patch` as a fix for this. As part of this change, the initialization logic was updated to clear `currently_booting_patch` and delete its artifacts (i.e., to treat a non-null value as a sign that the patch crashed during startup). Having this in …
=> refactor: only check whether a patch failed to boot on initialization

library/src/updater.rs
`updater.rs` had several tests that contained the same code to create a fake patch. This PR consolidates those into a shared function.
=> refactor: extract shared fake patch test logic into function

library/src/cache/patch_manager.rs, library/src/cache/updater_state.rs, library/src/network.rs, library/src/updater.rs
Updates our patch check logic to:
- Record patch numbers that fail to boot in a list of "known bad" patches.
- When making a patch check request, don't send a patch number. Instead, if there is a patch available for download, check whether we currently have the patch installed and ignore the new patch if so.
- If the server responds with a patch number that we have marked bad, do not attempt to download or install it.
=> feat: track known_bad_patches instead of highest_seen_patch to support rollbacks

library/src/c_api/mod.rs, library/src/cache/patch_manager.rs, library/src/cache/updater_state.rs, library/src/lib.rs, library/src/network.rs, library/src/test_utils.rs, library/src/updater.rs
Adds rollback support.
If the response to a patch check request tells us there are rolled back patches, delete them and ensure we don't try to boot from them in the future.
=> feat: add rollback support

library/src/network.rs, library/src/updater.rs
Makes the `patch_check_request` helper function a proper constructor.
=> refactor: make patch_check_request a constructor

library/src/updater.rs
Similar logs exist for reporting launch start and reporting launch failure.
=> chore: log when reporting successful launch

library/src/events.rs, library/src/network.rs, library/src/updater.rs
Adds an optional `message` field to the PatchEvent object.
=> feat: add message to patch event

library/src/android.rs, library/src/c_api/mod.rs, library/src/cache/disk_io.rs, library/src/cache/patch_manager.rs, library/src/cache/signing.rs, library/src/cache/updater_state.rs, library/src/config.rs, library/src/lib.rs, library/src/logging.rs, library/src/logging_macros.rs, library/src/network.rs, library/src/updater.rs
Adds `shorebird_info` etc macros to wrap logging macros from the `log` crate. These have the same function signatures as their `log` counterparts, but prepend `[shorebird]` for easier grepping.
Sample logs:
```
10-16 18:03:04.383  9690  9712 I flutter : updater::updater: [shorebird] Patch check response: PatchCheckResponse { patch_available: true, patch: Some(Patch { number: 1, hash: "92841966822f30cb9ae46a896e364ea2ee388403d93a22d275216e5c4305ffa9", download_url: "https://cdn.shorebird.cloud/api/v1/patches/6b193e92-9ff9-4263-9456-43f611244eea/android/aarch64/105960/dlc.vmcode", hash_signature: None }), rolled_back_patch_numbers: Some([]) }
10-16 18:03:04.673  9690  9712 I flutter : updater::updater: [shorebird] Patch 1 successfully downloaded. It will be launched when the app next …
```
=> feat: prepend all log messages with "[shorebird]"

library/src/cache/updater_state.rs
Fixes https://github.com/shorebirdtech/shorebird/issues/2612
=> fix: reset patches when updater state fails to deserialize

shorebird_code_push/lib/src/shorebird_updater.dart
=> docs: Clarify that update() Future only completes when download is done.

shorebird_code_push/pubspec.yaml
The changes in 2.0.0 do not exist in Flutter 3.24.4, so we should only allow for Flutter 3.24.5 and above.
Fixes https://github.com/shorebirdtech/shorebird/issues/2628
=> fix: increase minimum flutter version to 3.24.5

cspell.config.yaml, library/.cargo/config.toml
We currently do this for patch. Without this flag, the updater failed to link into the Flutter engine with the following:
```
...
b"LINK : warning LNK4217: symbol 'qsort' defined in 'libucrt.lib(qsort.obj)' is imported by 'updater.lib(cover.o)' in function 'COVER_ctx_init'\r\n"
b'updater.lib(std-b84ff5acd6bc244a.std.bacbcc9a321ad2c6-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol __imp_GetUserProfileDirectoryW referenced in function _ZN3std3env8home_dir17h0161835f45803d72E\r\n'
b'updater.lib(zdict.o) : error LNK2019: unresolved external symbol __imp_clock referenced in function ZDICT_clockSpan\r\n'
b'updater.lib(fastcover.o) : error LNK2001: unresolved external symbol __imp_clock\r\n'
b'updater.lib(cover.o) : error LNK2001: unresolved external symbol __imp_clock\r\n' …
```
=> fix: build updater with static runtime to prevent flutter engine build linking errors

library/src/updater.rs
Because windows works just like Android, and because Windows doesn't have to root around in the app bundle to find a libapp.so, we need to provide a platform-specific patch_base function.
=> feat: add windows support

shorebird_code_push/lib/src/shorebird_updater.dart, shorebird_code_push/test/src/shorebird_updater_test.dart
Override toString() in `ReadPatchException` and `UpdateException` classes as pointed out in (#253 ).
=> feat(shorebird_code_push): override `toString` in exceptions

shorebird_code_push/CHANGELOG.md, shorebird_code_push/pubspec.yaml
- chore(shorebird_code_push): v2.0.3
=> chore(shorebird_code_push): v2.0.3
